name: Android Build

on:
  workflow_dispatch:

jobs:
  build:
      
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./MobileFrontend
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Make gradlew executable
        run: chmod +x ./gradlew
          
      - name: Run Linter
        run: ./gradlew lint
          
      - name: Run Tests
        run: ./gradlew test
        
      - name: Build Project
        run: ./gradlew assemble

      - name: Upload Reports
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: MobileFrontend/app/build/reports
