name: React Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches: [main]

jobs:
  Jest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./WebFrontend/esports-player-finder
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          npm install 
          npm test
